-- Migration 020: Create Number_Calls table and seed default phrases
CREATE TABLE IF NOT EXISTS Number_Calls (
  number       INTEGER      PRIMARY KEY CHECK (number BETWEEN 1 AND 90),
  call_text    TEXT         NOT NULL,
  default_text TEXT         NOT NULL,
  audio_url    TEXT         DEFAULT NULL,
  call_mode    VARCHAR(10)  DEFAULT 'Text' CHECK (call_mode IN ('Text', 'Audio'))
);

-- Seed default phrases
INSERT INTO Number_Calls (number, call_text, default_text) VALUES
(1, 'Son of a gun, number one.', 'Son of a gun, number one.'),
(2, 'One little duck, number two.', 'One little duck, number two.'),
(3, 'Cup of tea, number three.', 'Cup of tea, number three.'),
(4, 'Knock at the door, number four.', 'Knock at the door, number four.'),
(5, 'Man alive, number five.', 'Man alive, number five.'),
(6, 'Tom Mix, number six.', 'Tom Mix, number six.'),
(7, 'Lucky for some, lucky seven.', 'Lucky for some, lucky seven.'),
(8, 'Garden gate, number eight.', 'Garden gate, number eight.'),
(9, 'Doctor''s orders, number nine.', 'Doctor''s orders, number nine.'),
(10, 'A big fat hen, one and zero, ten.', 'A big fat hen, one and zero, ten.'),
(11, 'Legs eleven, one and one, eleven.', 'Legs eleven, one and one, eleven.'),
(12, 'One dozen, one and two, twelve.', 'One dozen, one and two, twelve.'),
(13, 'Unlucky for some, one and three, thirteen.', 'Unlucky for some, one and three, thirteen.'),
(14, 'Valentine''s Day, one and four, fourteen.', 'Valentine''s Day, one and four, fourteen.'),
(15, 'Young and keen, one and five, fifteen.', 'Young and keen, one and five, fifteen.'),
(16, 'Sweet sixteen, one and six, sixteen.', 'Sweet sixteen, one and six, sixteen.'),
(17, 'Dancing queen, one and seven, seventeen.', 'Dancing queen, one and seven, seventeen.'),
(18, 'Coming of age, one and eight, eighteen.', 'Coming of age, one and eight, eighteen.'),
(19, 'Goodbye teens, one and nine, nineteen.', 'Goodbye teens, one and nine, nineteen.'),
(20, 'One score, two and zero, twenty.', 'One score, two and zero, twenty.'),
(21, 'Key to the door, two and one, twenty-one.', 'Key to the door, two and one, twenty-one.'),
(22, 'Two little ducks, two and two, twenty-two.', 'Two little ducks, two and two, twenty-two.'),
(23, 'Thee and me, two and three, twenty-three.', 'Thee and me, two and three, twenty-three.'),
(24, 'Two dozen, two and four, twenty-four.', 'Two dozen, two and four, twenty-four.'),
(25, 'Duck and dive, two and five, twenty-five.', 'Duck and dive, two and five, twenty-five.'),
(26, 'Pick and mix, two and six, twenty-six.', 'Pick and mix, two and six, twenty-six.'),
(27, 'Gateway to heaven, two and seven, twenty-seven.', 'Gateway to heaven, two and seven, twenty-seven.'),
(28, 'In a state, two and eight, twenty-eight.', 'In a state, two and eight, twenty-eight.'),
(29, 'Rise and shine, two and nine, twenty-nine.', 'Rise and shine, two and nine, twenty-nine.'),
(30, 'Burlington Bertie, three and zero, thirty.', 'Burlington Bertie, three and zero, thirty.'),
(31, 'Get up and run, three and one, thirty-one.', 'Get up and run, three and one, thirty-one.'),
(32, 'Buckle my shoe, three and two, thirty-two.', 'Buckle my shoe, three and two, thirty-two.'),
(33, 'All the threes, thirty-three.', 'All the threes, thirty-three.'),
(34, 'Ask for more, three and four, thirty-four.', 'Ask for more, three and four, thirty-four.'),
(35, 'Jump and jive, three and five, thirty-five.', 'Jump and jive, three and five, thirty-five.'),
(36, 'Three dozen, three and six, thirty-six.', 'Three dozen, three and six, thirty-six.'),
(37, 'More than eleven, three and seven, thirty-seven.', 'More than eleven, three and seven, thirty-seven.'),
(38, 'Christmas cake, three and eight, thirty-eight.', 'Christmas cake, three and eight, thirty-eight.'),
(39, 'Thirty-nine steps, three and nine, thirty-nine.', 'Thirty-nine steps, three and nine, thirty-nine.'),
(40, 'Life begins at forty, four and zero, forty.', 'Life begins at forty, four and zero, forty.'),
(41, 'Time for fun, four and one, forty-one.', 'Time for fun, four and one, forty-one.'),
(42, 'Winnie the Pooh, four and two, forty-two.', 'Winnie the Pooh, four and two, forty-two.'),
(43, 'Down on your knees, four and three, forty-three.', 'Down on your knees, four and three, forty-three.'),
(44, 'All the fours, forty-four.', 'All the fours, forty-four.'),
(45, 'Halfway there, four and five, forty-five.', 'Halfway there, four and five, forty-five.'),
(46, 'Up to tricks, four and six, forty-six.', 'Up to tricks, four and six, forty-six.'),
(47, 'Four and seven, forty-seven.', 'Four and seven, forty-seven.'),
(48, 'Four dozen, four and eight, forty-eight.', 'Four dozen, four and eight, forty-eight.'),
(49, 'PC forty-nine, four and nine, forty-nine.', 'PC forty-nine, four and nine, forty-nine.'),
(50, 'Half a century, five and zero, fifty.', 'Half a century, five and zero, fifty.'),
(51, 'Tweak of the thumb, five and one, fifty-one.', 'Tweak of the thumb, five and one, fifty-one.'),
(52, 'Pack of cards, five and two, fifty-two.', 'Pack of cards, five and two, fifty-two.'),
(53, 'Stuck in a tree, five and three, fifty-three.', 'Stuck in a tree, five and three, fifty-three.'),
(54, 'Clean the floor, five and four, fifty-four.', 'Clean the floor, five and four, fifty-four.'),
(55, 'All the fives, fifty-five.', 'All the fives, fifty-five.'),
(56, 'Was she worth it?, five and six, fifty-six.', 'Was she worth it?, five and six, fifty-six.'),
(57, 'Heinz varieties, five and seven, fifty-seven.', 'Heinz varieties, five and seven, fifty-seven.'),
(58, 'Make them wait, five and eight, fifty-eight.', 'Make them wait, five and eight, fifty-eight.'),
(59, 'Brighton line, five and nine, fifty-nine.', 'Brighton line, five and nine, fifty-nine.'),
(60, 'Five dozen, six and zero, sixty.', 'Five dozen, six and zero, sixty.'),
(61, 'Baker''s bun, six and one, sixty-one.', 'Baker''s bun, six and one, sixty-one.'),
(62, 'Turn the screw, six and two, sixty-two.', 'Turn the screw, six and two, sixty-two.'),
(63, 'Tickle me, six and three, sixty-three.', 'Tickle me, six and three, sixty-three.'),
(64, 'Red raw, six and four, sixty-four.', 'Red raw, six and four, sixty-four.'),
(65, 'Old age pension, six and five, sixty-five.', 'Old age pension, six and five, sixty-five.'),
(66, 'Clickety click, six and six, sixty-six.', 'Clickety click, six and six, sixty-six.'),
(67, 'Made in heaven, six and seven, sixty-seven.', 'Made in heaven, six and seven, sixty-seven.'),
(68, 'Saving grace, six and eight, sixty-eight.', 'Saving grace, six and eight, sixty-eight.'),
(69, 'Either way up, six and nine, sixty-nine.', 'Either way up, six and nine, sixty-nine.'),
(70, 'Three score and ten, seven and zero, seventy.', 'Three score and ten, seven and zero, seventy.'),
(71, 'Bang on the drum, seven and one, seventy-one.', 'Bang on the drum, seven and one, seventy-one.'),
(72, 'Six dozen, seven and two, seventy-two.', 'Six dozen, seven and two, seventy-two.'),
(73, 'Queen bee, seven and three, seventy-three.', 'Queen bee, seven and three, seventy-three.'),
(74, 'Hit the floor, seven and four, seventy-four.', 'Hit the floor, seven and four, seventy-four.'),
(75, 'Strive and strive, seven and five, seventy-five.', 'Strive and strive, seven and five, seventy-five.'),
(76, 'Trombones, seven and six, seventy-six.', 'Trombones, seven and six, seventy-six.'),
(77, 'Sunset strip, seven and seven, seventy-seven.', 'Sunset strip, seven and seven, seventy-seven.'),
(78, 'Heaven''s gate, seven and eight, seventy-eight.', 'Heaven''s gate, seven and eight, seventy-eight.'),
(79, 'One more time, seven and nine, seventy-nine.', 'One more time, seven and nine, seventy-nine.'),
(80, 'Eight and blank, eight and zero, eighty.', 'Eight and blank, eight and zero, eighty.'),
(81, 'Stop and run, eight and one, eighty-one.', 'Stop and run, eight and one, eighty-one.'),
(82, 'Straight on through, eight and two, eighty-two.', 'Straight on through, eight and two, eighty-two.'),
(83, 'Time for tea, eight and three, eighty-three.', 'Time for tea, eight and three, eighty-three.'),
(84, 'Seven dozen, eight and four, eighty-four.', 'Seven dozen, eight and four, eighty-four.'),
(85, 'Staying alive, eight and five, eighty-five.', 'Staying alive, eight and five, eighty-five.'),
(86, 'Between the sticks, eight and six, eighty-six.', 'Between the sticks, eight and six, eighty-six.'),
(87, 'Torquay in Devon, eight and seven, eighty-seven.', 'Torquay in Devon, eight and seven, eighty-seven.'),
(88, 'Two fat ladies, eight and eight, eighty-eight.', 'Two fat ladies, eight and eight, eighty-eight.'),
(89, 'Nearly there, eight and nine, eighty-nine.', 'Nearly there, eight and nine, eighty-nine.'),
(90, 'Top of the house, nine and zero, ninety.', 'Top of the house, nine and zero, ninety.')
ON CONFLICT (number) DO NOTHING;
