export const nepaliPhrases: Record<number, string> = {
  1: "Dahine bata herda Shahrukh Khan, debre bata herda Aamir Khan, agadi bata herda Hanuman, single number one, eklo sankhya ek.",
  2: "Dhami jhakri le bhancha om mantar kichu, single number two, eklo sankhya dui.",
  3: "Darjeeling ko chiya, kasto mitho baha, single number three, eklo sankhya tin.",
  4: "Char disha char dham, sabai bhanda ramro hamro gaun, single number four, eklo sankhya char.",
  5: "Pancha pandav bhai bhai, kasto ramro saili ra maili, single number five, eklo sankhya paach.",
  6: "Cricket ma lagayo chakka, kasto ramro thakka, single number six, eklo sankhya chha.",
  7: "Saat din ko saptaha, ghumna jau chowrasta, single number seven, eklo sankhya saat.",
  8: "Aath disha bata aayo bataas, single number eight, eklo sankhya aath.",
  9: "Nau durga bhawani, kasto ramro jawani, single number nine, eklo sankhya nau.",
  10: "Das avatar narayan ko katha, one and zero, ten, ek ra sunya das.",
  11: "Dui boka thoka thok, one and one, eleven, ek ra ek eghara.",
  12: "Baara mahina ko ek barsa, one and two, twelve, ek ra dui baara.",
  13: "Tera haat ko patuki, kasto ramro nautanki, one and three, thirteen, ek ra tin tera.",
  14: "Chaudha anchal pachattar jilla, one and four, fourteen, ek ra char chaudha.",
  15: "Pandra din ko paksha, hami sabai ko raksha, one and five, fifteen, ek ra paach pandra.",
  16: "Sohra barsha ko umerma, pare ma ta mayama, one and six, sixteen, ek ra chha sohra.",
  17: "Satra gate mela lagne thau, one and seven, seventeen, ek ra saat satra.",
  18: "Athara puran hindu ko grantha, one and eight, eighteen, ek ra aath athara.",
  19: "Unnis bis ko pharak, bato ko kasto ramro sadak, one and nine, nineteen, ek ra nau unnis.",
  20: "Bis nakh bis bakh, two and zero, twenty, dui ra sunya bis.",
  21: "Ekkais toph ko salami, two and one, twenty-one, dui ra ek ekkais.",
  22: "Dui ra dui milera bais, jiban ko naya thalani, two and two, twenty-two, dui ra dui bais.",
  23: "Teis gate ko gham, kasto mitho aam, two and three, twenty-three, dui ra tin teis.",
  24: "Chaubis ghanta khatai, kasto dherai ghumai, two and four, twenty-four, dui ra char chaubis.",
  25: "Momo khadai baschis, two and five, twenty-five, dui ra paach pachis.",
  26: "Chabbis gate jado ko mahina, two and six, twenty-six, dui ra chha chabbis.",
  27: "Satais nakshatra aakash ko tara, two and seven, twenty-seven, dui ra saat satais.",
  28: "Athais tithi purnima ko raat, two and eight, twenty-eight, dui ra aath athais.",
  29: "Untis gate mahina ko antia, two and nine, twenty-nine, dui ra nau untis.",
  30: "Mahina ko din tis, kasto ramro jhilikis, three and zero, thirty, tin ra sunya tis.",
  31: "Ektis din ko mahina, herna ma kasto ramro aaina, three and one, thirty-one, tin ra ek ektis.",
  32: "Batis dath dekhera hasyo, three and two, thirty-two, tin ra dui batis.",
  33: "Tin ra tin milera tettis, bato ma bhetis, three and three, thirty-three, tin ra tin tettis.",
  34: "Chautis ko chot, dil ma lagyo khot, three and four, thirty-four, tin ra char chautis.",
  35: "Paitis umer dhalis, kasto dherai karalis, three and five, thirty-five, tin ra paach paitis.",
  36: "Chaurasta ma bhetis, three and six, thirty-six, tin ra chha chhattis.",
  37: "Saitis gate ko jatra, hinda hundai vayo khatra, three and seven, thirty-seven, tin ra saat saitis.",
  38: "Athatis ko aat, kasto dherai baat, three and eight, thirty-eight, tin ra aath athatis.",
  39: "Unanchalis ko joro, kasto aayo moro, three and nine, thirty-nine, tin ra nau unanchalis.",
  40: "Char wota zero chalis, bato ma kasto ufris, four and zero, forty, char ra sunya chalis.",
  41: "Ekchalis ma pachi pachi, four and one, forty-one, char ra ek ekchalis.",
  42: "Bialis ko line, kasto ramro shine, four and two, forty-two, char ra dui bialis.",
  43: "Tichalis ma tita, kasto dherai chinta, four and three, forty-three, char ra tin tichalis.",
  44: "Chor haru lai police le khedyo, four and four, forty-four, char ra char chawalis.",
  45: "Paitalis ko bishram, kasto ramro kaam, four and five, forty-five, char ra paach paitalis.",
  46: "Chhialis ma chhutti, kasto mitho ruti, four and six, forty-six, char ra chha chhialis.",
  47: "Saichalis ko sainik, desh ko kasto ramro manik, four and seven, forty-seven, char ra saat saichalis.",
  48: "Athchalis ko aat, bhitra bhitra baat, four and eight, forty-eight, char ra aath athchalis.",
  49: "Bacchon ke liye Horlicks, badon ke liye wine, four and nine, forty-nine, char ra nau unchas.",
  50: "Half century pura vayo pachaas, four and zero, fifty, paach ra sunya pachaas.",
  51: "Ekanna ma ek, kasto ramro cake, five and one, fifty-one, paach ra ek ekanna.",
  52: "Baanna patti taas ko, khel kasto ramro aash ko, five and two, fifty-two, paach ra dui baanna.",
  53: "Sikkim ko dhan, hariyo ban, swarga ko phulbari, five and three, fifty-three, paach ra tin tirpan.",
  54: "Chauwanna ko chauka, yo po ho ta mauka, five and four, fifty-four, paach ra char chauwanna.",
  55: "Budo umer ma bachpan, five and five, fifty-five, paach ra paach pachpanna.",
  56: "Chhapanna inch ko chhati, kasto ramro maati, five and six, fifty-six, paach ra chha chhapanna.",
  57: "Santanna ko kranti, sabai tira shanti, five and seven, fifty-seven, paach ra saat santanna.",
  58: "Anthanna ma aath, hami sabai ko saath, five and eight, fifty-eight, paach ra aath anthanna.",
  59: "Unsathi ko un, gham lageko jun, five and nine, fifty-nine, paach ra nau unsathi.",
  60: "Sathi haru ko jamghat sathi, six and zero, sixty, chha ra sunya sathi.",
  61: "Eksathi ma ek, bato ma kasto ramro bhek, six and one, sixty-one, chha ra ek eksathi.",
  62: "Kutu ma kutu supari dana, six and two, sixty-two, chha ra dui basatthi.",
  63: "Tirsathi ko tir, kasto dherai bhir, six and three, sixty-three, chha ra tin tirsathi.",
  64: "Chausathi ko chau, yo po ho ta thau, six and four, sixty-four, chha ra char chausathi.",
  65: "Paisathi ma paisa, life ma kasto kaisa, six and five, sixty-five, chha ra paach paisathi.",
  66: "Chhaisathi ma chakka, sabai jana thakka, six and six, sixty-six, chha ra chha chhaisathi.",
  67: "Sarsathi ma sar, bato ma kasto dherai darr, six and seven, sixty-seven, chha ra saat sarsathi.",
  68: "Athsathi ma aath, ghumna jau na math, six and eight, sixty-eight, chha ra aath athsathi.",
  69: "Unansattari ko un, sun ko jasto gun, six and nine, sixty-nine, chha ra nau unansattari.",
  70: "Sattari saal ko budo, kasto dherai judo, seven and zero, seventy, saat ra sunya sattari.",
  71: "Ekhattar ma ek, kasto ramro lek, seven and one, seventy-one, saat ra ek ekhattar.",
  72: "Bahattar ma baa, sabai bhanda ma, seven and two, seventy-two, saat ra dui bahattar.",
  73: "One of the historical place of Sikkim, Khecheopalri, seven and three, seventy-three, saat ra tin tihattar.",
  74: "Chauhattar ma chau, khana mitho bhau, seven and four, seventy-four, saat ra char chauhattar.",
  75: "Pachhattar ma paach, kasto ramro naach, seven and five, seventy-five, saat ra paach pachhattar.",
  76: "Chhahattar ma chha, kasto ramro thaa, seven and six, seventy-six, saat ra chha chhahattar.",
  77: "Saat ra saat sathattar, bato ma chha patthar, seven and seven, seventy-seven, saat ra saat sathattar.",
  78: "Athattar ma aath, kasto ramro haat, seven and eight, seventy-eight, saat ra aath athattar.",
  79: "Unasi ko un, kasto mitho dhun, seven and nine, seventy-nine, saat ra nau unasi.",
  80: "Assi barsha ko aama, ghumna gaye ghaama, eight and zero, eighty, aath ra sunya assi.",
  81: "Ekasi ma ek, bato ma hera bhek, eight and one, eighty-one, aath ra ek ekasi.",
  82: "Biasi ma bi, kasto ramro chiya ki, eight and two, eighty-two, aath ra dui biasi.",
  83: "Tirasi ko tir, man ma kasto ramro pir, eight and three, eighty-three, aath ra tin tirasi.",
  84: "Chaurasi ko puja, khana mitho bhuja, eight and four, eighty-four, aath ra char chaurasi.",
  85: "Pachasi ma paach, sabai mili naach, eight and five, eighty-five, aath ra paach pachasi.",
  86: "Chhiasi ma chha, kasto ramro hawa, eight and six, eighty-six, aath ra chha chhiasi.",
  87: "Satasi ma saat, purnima ko raat, eight and seven, eighty-seven, aath ra saat satasi.",
  88: "Dui mota bhalu sangai hindai, eight and eight, eighty-eight, aath ra aath athasi.",
  89: "Unanabbe ma un, kasto ramro sun, eight and nine, eighty-nine, aath ra nau unanabbe.",
  90: "Khel ko antim number, top of the house blind ninety, nine and zero, ninety, nau ra sunya nabbe."
};
